### ISSUE TITLE
훈련기관 과정신청

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#102]
1. 정보 미입력시 팝업 알림사항에

항목을 다 입력후 저장 안한경우 팝업이 "기본정보부터 입력해야 합니다" 라고 뜨는데,

기본정보를 저장하셔야 합니다. 로 수정 

2. 과정개요의 휴무일 출석부 반영을 위해 여러 일자가 중복으로 선택되도록 수정

3. 강사정보 등록시 주민등록번호 생년월일로 변경 요망

4. 강사정보 등록시 아래로 스크롤이 안됨 (다른 추가등록 팝업에 스크롤 없음)

5. 훈련내용 등록시 양식다운 클릭하면 오류 발생 

6. 훈련내용의 훈련 일정 등록시 "일수"를 "일차"로 하고  저장 후 보여질때는 일차 오름차순으로 보이도록 정렬 (중간에 삭제 후 재등록시 순서데로 보이도록 해야함)

7. 신청완료 후부가정보 등록정보 확인 과정에서 부가정보 훈련기관 홍보이미지 클릭시 화면 미노출

**Comment by lalalaho** [comment]
2. 기능변경 

1. 수정완료.
3. 수정완료
4. 수정완료
5. 수정완료
6. 수정완료.
7.수정완료.
