### ISSUE TITLE
[감리]관리자 공통

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#105]
1)관리정보     
- 관리자 접속 비밀번호 변경 시 기존 비밀번호(admin 계정   비밀번호 1111) 입력 후  확인 버튼 클릭 시
  "기존 비밀번호가 맞지   않습니다" 오류 발생

2)회원관리      
- 회원정보 신규 등록시 비밀번호가 6자리 이상 가능하도록   제공하고 있음       (*공공기관 경우 영문,
  숫자,특수 문자 조합 9자리 이상 권고)

3)게시판 공통 
- 첨부파일 3개까지 등록이 가능하나 파일첨부 안내에 5개로   제공하고 있음

4)문의하기      
- 문의내용 상세 화면 시 문의내용 및 답변내용에 포커스가   가능하여 사용자로 하여금  혼란을 줄 수 
  있음. Readony로 처리필요       
- 답변내용에 입력을 안하고, 등록버튼 클릭을 해도 답변완료   상태가 됨          

5)자주찾는질문     
 - 상세내용에서 삭제 삭제확인 알람 미제공

6)접속통계     
 - 기간별 접속통계(전체 방문자수, 금일 방문자수,어제방문자수)   수치 기능 오류   (기간 변경 후 검색 
   시에도 동일한 통계 정보 제공)

7)공통코드     
 - 코드그룹의 코드 삭제 시 코드 그룹까지 삭제됨

**Comment by kissgrrr** [comment]
admin / 고용지원!@#$   로그인해주세요.

**Comment by kissgrrr** [comment]
문의하기 -  상세화면 Readony 적용 중이며 화면 선택 시 커서 안생기게 할 수는 없습니다.
접속통계 - 전체 방문자수, 금일 방문자수,어제방문자수는 기간의 영향을 받지않습니다.
코드 삭제 시 코드그룹 삭제 안됨..(정상작동중입니다.)
