### ISSUE TITLE
[감리]관리자_행정지원

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#107]
[MAIN]
1)대시보드 기능
 - 훈련실시 현황 통계 수치 확인 필요(훈련중,중도탈락 등)

[훈련기관관리]
1)훈련기관정보
 - 훈련기관 정보관리 화면에서 비밀번호 변경 시 기존 비밀번호를 입력하지 않음
2)훈련과정신청
 - 강사 등록 시 주민등록번호 뒷7자리 저장 안됨
 - 훈련시설 등록 후 조회화면에서 수정버튼 클릭 시 팝업화면에서 오류발생 
 - 훈련교재 등록 화면에서 파일첨부 후 훈련교재 수정화면에서 다운로드 불가 
3) 훈련과정 정보변경신청
 - 조회화면에서 승인일자 입력 오류 발생
4) 훈련과정 정보변경 신청이력
 - 조회버튼 미제공
 - 조회 후 훈련과정명 클릭 시 상세화면으로 로딩되지 않음
5) 훈련차수관리
  - 조회화면의 차수와 상세화면의 차수가 일치 하지 않음
  - 훈련차수에 대해 신규 등록을 하였으나 신규 등록 데이터가 조회되지 않음
  - 조회조건(년도,훈련명)에 따른 검색이 되지 않음

[훈련생관리]
1) 기관별 훈련생관리 기능 점검 불가
2) 훈련생별 훈련이력조회 기능 점검 불가

[출결관리]
1)출석부조회
 - 개인별 출결현황 팝업에서 훈련생 정보 수정 버튼 클릭 시 저장후 화면이 Clear됨
 - 검색조건의 훈련생 수와 조회된 훈련생수가 일치 하지 않음
 - 외출수기 입력 시 조회조건의 개인식별 용으로 주민등록번호 입력을 요구하고 있음

[훈련현황관리]
1)일일 훈련실시 현황보고
 - 일별 검색 안됨

**Comment by lalalaho** [comment]
[MAIN]
1) 2차 오픈 후 적용 예정.

[훈련기관관리]
훈련기관 정보관리 화면에서 비밀번호 변경 시 기존 비밀번호를 입력하지 않음
-> 관리자 에서는 직접변경 , 기관 로그인 시 비밀번호 확인 후 변경

2)훈련과정신청
강사 등록 시 주민등록번호 뒷7자리 저장 안됨 -> 없어짐.
훈련시설 등록 후 조회화면에서 수정버튼 클릭 시 팝업화면에서 오류발생 -> 수정완료
훈련교재 등록 화면에서 파일첨부 후 훈련교재 수정화면에서 다운로드 불가 -> 보기창 다운로드 가능
훈련과정 정보변경신청 조회화면에서 승인일자 입력 오류 발생 -> 기능변경
훈련과정 정보변경 신청이력 조회버튼 미제공 -> 훈련기관 훈련과정 변경시 자동 검색 기능 
조회 후 훈련과정명 클릭 시 상세화면으로 로딩되지 않음 -> 로딩 됨.
훈련차수관리 조회화면의 차수와 상세화면의 차수가 일치 하지 않음 -> 수정완료.
훈련차수에 대해 신규 등록을 하였으나 신규 등록 데이터가 조회되지 않음 -> 수정완료
조회조건(년도,훈련명)에 따른 검색이 되지 않음 -> 수정완료.

[훈련생관리]
기관별 훈련생관리 기능 점검 불가 
훈련생별 훈련이력조회 기능 점검 불가

[출결관리]
1)출석부조회
개인별 출결현황 팝업에서 훈련생 정보 수정 버튼 클릭 시 저장후 화면이 Clear됨 -> 수정완료
검색조건의 훈련생 수와 조회된 훈련생수가 일치 하지 않음 -> 수정완료
외출수기 입력 시 조회조건의 개인식별 용으로 주민등록번호 입력을 요구하고 있음

[훈련현황관리]
1)일일 훈련실시 현황보고

일별 검색 안됨 -> 정상동작.
