### ISSUE TITLE
[감리]사용자_PC

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#108]
[공통]
스크롤에 따라 움직이는 퀵메뉴로 인해 팝업창 닫기 버튼이 숨겨져 사용자 편의성 저하 우려 

[채용정보]
1)통합검색
 - 근무지역 선택불가
 - 검색결과에 총"10건"으로 표시되나, 데이터 없음
 - 경력 From To 검색조건 값 경계값 표지 Validatiom check 기능 미제공
 - 희망임금 From To 검색조건 값 경계값 표지 Validatiom check 기능 미제공
 - 공고등록일 라디오 버튼 처리로 기간 해제 불가
 - 맞춤정보저장 버튼 클릭시 "저장 실패했습니다" 오류 발생
2)직종별
 - 팝업창에서 2개 업체 체크 후 채용정보 비교하기 조회, 자세히 보기 클릭 후 
   이전 화면으로 되돌아 올 수 있는 방법이 없음.
   (단 워크넷 채용 공고 인 경우 새로운 창으로 제공하여, 이전 화면 접근 가능)  
 - 직종별 조회 후 모집업체 상세화면에서 알선요청하기 버튼 클릭시 
   "조회필패" 오류 발생

[인재정보]
1)통합검색
 -  연령 From To 검색조건 값 경계값 표지 Validatiom check 기능 미제공

[훈련기관]
1)훈련기관
 - 훈련기관 조회 후 과정보기 클릭 시 훈련과정 페이지로 Redirect 됨.이전화면 
   접근 불가

[고객센터]
1)문의사항
 - 문의사항 삭제 시 삭제확인 없이 삭제처리 됨
2) 부정행위신고센터
 - 내용 입력 후 제출하기 버튼 클릭 시 기능 작동 안됨

**Comment by lalalaho** [comment]
[훈련기관]
수정완료
