### ISSUE TITLE
훈련생 등록

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#111]
1.  검색 실명확인 버튼 교체
훈련생 정보 입력시 주민등록번호 입력 후 실명인증 후 검색 기능에서
실명인증과 검색의 아이콘 위치 변경 (실명인증 후 검색이 가능하므로 순서대로 배치 요망)

2. 계좌검증 기능 없음

3. 훈련생 등록 버튼 클릭하면 등록 후에 창전환 되지 않고 해당화면에 머물러 있음

**Comment by YCKO0923** [comment]
1. 수정필요
2. 계좌검증 불가( 추후 협의 필요)
3. 수정필요
