### ISSUE TITLE
훈련생관리>기관별훈련생 관리

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#119]
현재 시스템에는 훈련기관별 훈련생 관리에서 과정명 클릭시 훈련과정별 훈련생 리스트가 조회되록 되어 있고 훈련생 리스트 엑셀파일 다운기능이 있으나 

신규 구축 페이지에는 엑셀파일 다운기능이 없음

**Comment by lalalaho** [comment]
수정완료.
