### ISSUE TITLE
구직관리>등록>구직자수정

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#126]
구직등록 시 첨부했던 이력서 파일에 대한 '수정', '삭제' 불가능. '수정', '삭제' 기능 추가 필요

**Comment by match23** [comment]
기존에 없던 기능으로 추가개발해야 되는 사항.

**Comment by match23** [comment]
![image](https://user-images.githubusercontent.com/45932499/50754512-54972a80-1299-11e9-8ac7-89fe4562b513.png)

1.위와 같이 삭제 버튼을 추가하였음.
2. 상세 페이지에서 이미지 삭제 버튼 제거(수정 페이지에서만 삭제 가능)
3. 이미지 삭제 버튼도 동일하게 적용하였으며, 
    기존에 삭제시 삭제 히스토리용으로 팝업 호출후 삭제 처리 하였으나 
    히스토리 등록 없이 바로 처리되도록 수정함.
