### ISSUE TITLE
통계관리, 행정관리 접속 불가

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#128]
현 시각 기준 통계관리, 행정관리 탭 접속 불가
다른 탭(ex.구직관리) 조회 후 통계관리 및 행정관리 탭 클릭시 반응 없음

**Comment by YCKO0923** [comment]
통계관리/행정관리/ 예산관리(승인내역 제외) 는 2차 오픈시 확인 하실 수 있습니다.
