### ISSUE TITLE
구직관리>구직신청

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#129]
1. 희망임금
-  '최저임금' 미만으로 기재 시 '오류' 메시지 팝업 필요
- 팝업 : '최저임금 미만 입력 불가'

2. 홈페이지 공개여부 
-'공개','비공개' 하단 문구 수정 필요
- 공개 : '건설일드림넷'에 민감정보(주민등록번호 등)를 제외한 모든 자료가 공개됩니다.
- 비공개 : '건설일드림넷'에 구직등록사항이 공개되지 않아 구인업체에서 열람 불가능합니다.

3. 구직신청경로
- 필수체크 항목으로 변경 필요

**Comment by match23** [comment]
1. 현재 2019년 최저 임금으로 계산함 - 맞는지 확인 요망.
  2019년 최저임금 8,350원  최소일당(8시간기준)66,800원
2. 공개여부는 취업지원전산망, 워크넷, 비공개로 분류변경됨.
  - 하단 설명내용 수정 전달 요망.
3. 완료
