### ISSUE TITLE
구직관리>등록

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#132]
등록시 비밀번호는

휴대폰번호로 임시비밀번호 보내기 위해서 휴대폰 번호를 등록하는게 맞다면.

휴대폰번호 입력의 기능은 문자 발송기능을 위해 구현한것인지 확인하여 주시고,

비밀번호 아래에 주석 표시 요망

**Comment by YCKO0923** [comment]
네. 구직자 등록 시 회원가입을 위한 비밀번호 문자발송 기능입니다.
비밀번호는 [약어][생성날짜][특수문자랜덤]로 발송되어지도록 개발되었습니다.
(예) cwma1005!

**Comment by match23** [comment]
주석이 필요하다면 문구 전달 요망.

**Comment by YCKO0923** [comment]
아래 문구는 아이디 필드 밑으로 붙혀주셔아 의미가 있는 것 같습니다.
※ 기존 회원가입이 되어 있는 회원은 비밀번호를 발송하지 않습니다.
