### ISSUE TITLE
구직관리>구직신청

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#138]
1. 구직재신청 : 구직재신청 시 기존에 동일한 직종으로 구직신청한 이력이 마감되지 않을 경우, 
동일 직종으로 재신청 불가능하게 조치 필요
2. 수정 : 수정화면에서 이력서 첨부파일 클릭시 오류페이지가 뜸
3. 수정 : 수정화면에서 '진행상태' 수정 관련
- 홈페이지 및 모바일앱을 통한 신청 건의 경우만 수정 가능.
- 센터등록 건의 경우는 '진행상태' 수정 불가능하도록 조치 필요

**Comment by YCKO0923** [comment]
전체 수정사항 확인 안됨
