### ISSUE TITLE
상담관리

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#146]
<구직>
1. 구직신청 시 희망지역 '관계없음'이라고 체크한 신청 건은 '관계없음'이라고 표시되도록 수정 필요(현재는 null값으로 표시됨)
2. 구직상담등록 부분 중 '상담내용' 구분 수정 필요
- 구인재신청 -> 구직재신청

<구인, 구직 공통>
1. 구직상담등록 부분 중 '상담구분' 분류 추가 필요
- 건설일드림넷 추가

**Comment by pcninc** [comment]
위의 구분 수정에 따라 '민원상담현황' 통계표 수정 필요(해당 부분은 추후 통계 관련 작업 시 협의 필요)

**Comment by YCKO0923** [comment]
1. 희망 지역2 가 상세화면에서 출력되지 않습니다.
2.  구직상담  > 상담구분에 [건설일드림넷 ] 항목을 추가해주세요..
3.  구인상담  > 상담구분에 [건설일드림넷 ] 항목을 추가해주세요..
