### ISSUE TITLE
사용자 > MY서비스

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#177]
로케이션 에서
첫번째 MY서비스 는 선택 시 마이서비스 메인화면으로 이동되어야하며
드롭다운 버튼이 없어야 합니다.

**Comment by kissgrrr** [comment]
드롭다운 버튼은 퍼블 요청이 필요합니다.

**Comment by YCKO0923** [comment]
이동확인 했습니다. pass 입니다~
드롭다운 버튼은 안보이게만 하면 되는데....퍼블이 꼭 필요하신 가요?

**Comment by YCKO0923** [comment]
퍼블 완료하여 메일로 드렸습니다.
