### ISSUE TITLE
MY서비스 > 수료증 발급조회

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#180]
수료처리된 훈련정보 미노출

**Comment by lalalaho** [comment]
현재 기존 회원 정보에 주민등록번호가 존재하여 노출이 되었으나 주민번호 제외로
주민번호를 입력하여야 검색이 가능하도록 되어있음.

주민번호 입력 후 조회 시, 
가입 회원명 과 수강생 회원명이 동일해야 검색이 가능 하도록 되어있음.

기존 휴대폰 번호까지 비교하였으나 휴대폰 번호 비교는 제외 시켜 놓음.

postcorea 회원 이름 변경 하였음.

검색 할 주민번호 
661116
1798035
