### ISSUE TITLE
상담관리

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#182]
1. 구인상담 등록 / 수정 안됨.
2. 구직상담 상담자 노출안됨.
3. 구직수정 시 내용 초기화 됨.
4. 민원상담현황 데이터 조회 안됨

**Comment by match23** [comment]
수정완료. 
* job_admin 계정의 경우 등록된 센터가 없는 계정으로 해당 계정으로는 테스트 불가
따로 테스트 아이디 생성 해야됨.

**Comment by YCKO0923** [comment]
테스트 아이디 생성해 주세요

**Comment by match23** [comment]
센터 로그인
아이디 / 패스워드
C1101 / plan227

센터 직원 로그인
아이디 / 패스워드
jk3869061 / plan227

**Comment by YCKO0923** [comment]
등록 시 상담자가 출력되지 않습니다.
