### ISSUE TITLE
MY서비스 > 구직신청

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#191]
kyc0422 / rlghlrwk0923! 

계정으로 접근해보시면 구직신청정보가 1건 존재합니다.
없을 경우에는 담당센터를 선택할 수 있는데
있으면 담당센터가 선택이 안되는 것 같습니다.
이유가 무엇인가요?

**Comment by match23** [comment]
동일 주민번호로 다건의 다른계정이 등록된 경우(데이터 오류).
논의한 내용대로 구직테이블에서 주민번호당 1개의 계정 연결되도록 수정.
