### ISSUE TITLE
상담관리 > 구직상담(구인상담 포함)

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#195]
기관 계정으로 로그인하여 진행했습니다.
등록 시 관라자명이 출력되지도. 입력되지도 않습니다.

**Comment by match23** [comment]
논의한 내용으로 수정,
1.담당직원 로그인시 상담입력 가능
2. 총괄/기관 계정 로그인시 상담불가(상담입력/수정 버튼 비노출)
