### ISSUE TITLE
구인관리 > 상세

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#212]
구인신청 상세에서 [인증] 버튼 클릭 시 500에러

**Comment by match23** [comment]
1. 정상확인 (테스트 구직자/ 고영철, 김성진) 인증 취소 후 재인증해봤음.
* 해당 오류 발생 원인은 수정 후 sms 발송단계에서 오류가 날 경우인데 
sms발송 요청 프로시저가 있는 DB쪽 연결이 일시적인 문제가 있던것으로 판단됨.
현재 500에러 발생시 공통 에러 페이지 출력되도록 수정함.
