### ISSUE TITLE
기업회원 가입시 ID중복체크 안됨

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#39]
개인회원으로 등록된 ID 입력 후 중복확인결과 사용가능한 ID라고 표기됨

**Comment by YCKO0923** [comment]
PM님. 기존에 개인회원과 기업회원 테이블이 분리되어 있어서 그렇습니다.
이 부분에 대한 니즈가 없어서 현행을 유지하려고 하는데 문제될 소지가 있을까요?

**Comment by pcninc** [comment]
공제회와 협의필요한 사항인것 같습니다.
