### ISSUE TITLE
행정 > 훈련과정신청 > 강사정보 > 강사추가 팝업

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#48]
1. 강사정보 팝업 사이즈가 맞지않습니다..
저장 버튼이 보이는데까지 맞춰주세요..
그리고...이 부분 공통레이어 팝업인데.. 나중에 해주세요...ㅎㅎ

2. 첨부파일이 수정페이지에서 보이지 않아요.

**Comment by lalalaho** [comment]
1. 사이즈가 너무 김 화면 짧은 곳에서는 스크롤이 없는 경우 밑에를 볼 수 있는 방법 없음.
일단 길이는 700px로 조절

2. 첨부파일 완료.
