### ISSUE TITLE
행정 > 훈련과정신청 > 시설/장비/교재 > 장비추가 버튼

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#49]
1. 팝업 사이즈 조절해주세요. 저장/닫기 버튼 보이도록..
2. 첨부된 사진 선택 시 레이어 팝업에 출력되는 이미지가 실 등록된 이미지랑 상이합니다.
디폴트로 이미지가 박혀있는것같아요.

**Comment by lalalaho** [comment]
1. 조정완료
2. 수정완료
