### ISSUE TITLE
훈련생 관리> 기관별 훈련생 관리 > 과정별 훈련생 리스트 

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#53]
1. 훈련생 목록 > 출석일수(기간별) 데이터 출력확인 필요. 
조회기간내의 훈련일수로 표시필요. (예) 8.1~8.15 기간 조회시 해당기간 출석일수 별도 표시

2. 검색 필드에 [오늘] 기능 추가 필요
오늘 선택 시 훈련기간이 달력기간이 당일날짜로 출력되도록 처리

**Comment by lalalaho** [comment]
1. 출석일수 자체가 기간별 출석일수와 동일.

2. 오늘 출석일로 검색 자체가 불가능 기간단위로 검색 됨.
