### ISSUE TITLE
훈련생 관리 > 기관별 훈련생 관리 > 훈련생 상세정보 > 훈련생정보(Tab)

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#54]
1. 저장/목록/삭제 버튼 미동작, 저장 시 [사후정보] 탭으로 이동해야 합니다.
2. 문구변경: 사전상담일지 업로드 -> 사전상담일지
2-1. 첨부된 파일 [출력하기] 버튼 출력 필요

**Comment by lalalaho** [comment]
1. 수정완료
2. 수정완료
2-1 pdf외의 파일은 웹페이지에서 출력할 수 있는 방법이 없음.
      download 로 대체.
