### ISSUE TITLE
훈련생 관리 > 기관별 훈련생 관리 > 훈련생 상세정보 > 사후정보(Tab)

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#55]
1. 자격증취득정보 > 추가 버튼 선택 시 미동작
2. 상담정보 > 추가 버튼 선택 시 미동작
3. 데이터 입력 후 [저장] or [목록]버튼 선택 시 미동작
4. 취업정보에 취업기간 입력 시, 훈련개시일 이전 취업일 경우 취업 훈련일 중복 Alert창 출력 
“훈련개시일과 취업기간이 중복되었습니다”

**Comment by lalalaho** [comment]
1. 수정완료
2. 수정완료
3. 수정완료

**Comment by lalalaho** [comment]
4. 수정완료.
