### ISSUE TITLE
훈련생 관리 > 훈련생 확정 예정자 관리 

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#61]
1. 전체선택 셀렉트 박스 상/하에 있는 검은박스 삭제필요
2. 누적일수 표기 방법 수정 필요 / 시작일 기준으로 출결이 확인된 5일에 대한 출석일수 표시
(예: 5/3)
3. 출결보기 팝업 사이즈 스크롤 발생 하지 않도록 처리해주세요
4. 출별보기 팝업 > 훈련생 정보수정 버튼 클릭 시 성명, 주민등록번호를 포함한 모든항목이 초기화 됩니다...확인부탁드려요

**Comment by lalalaho** [comment]
1. 수정완료.
2. 수정완료.
3. 출석일수가 늘어지면 스크롤이 생길 수 밖에 없음. 출석일수 없을 때에는 안생기도록 수정
4.수정완료.
