### ISSUE TITLE
출결관리 > 출석부 조회

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#63]
1. 현재 기관/과정 선택 후 검색 시 리스트페이지가 나오는데요. 바로 전체 캘린더가 보일 수 있도록 처리해주세요. 검색 버튼 클릭 시 [출석월]을 필수값으로 지정
2. 엑셀다운로드 버튼 필요.
3. 훈련기관에서 지정한 과정별 휴무일 표시 필요.
4. 개시일/종료일 오름차순,내림차순 기능 미동작
5. 총출석일수 클릭 시 팝업 활성화 필요..현재 준비중
6. 검색 당일날짜 색 구분 표기 필요
7. 날짜 선택 시 이력관리 팝업 활성화 필요.

**Comment by lalalaho** [comment]
1. 출석월 필수값 설정 . 
2. 준비중
3. 준비중
4. 준비중
5. 준비중
6. 당일월 밖애 없음.
7. ??

**Comment by YCKO0923** [comment]
5. 준비끝나시면 말씀좀..
6. 조회시점일이 검색된 당월에 포함되어 있으면 해당일에 색구분 표기가 필요합니다.
7. 네. 일자를 선택하면 이력관리 팝업이 떠야합니다. (화면설계확인해주세요)

**Comment by lalalaho** [comment]
5. 수정완료
6. 수정완료
7. 수정완료
