### ISSUE TITLE
메인페이지 하단 패밀리사이트

### ISSUE THREAD

**Issue by pcninc** [lalalaho/cid#89]
홈페이지 하단의 패밀리 사이트에 

건설근로자공제회 홈페이지 (https://www.cwma.or.kr)

건설근로자 하나로 서비스 (https://1122.cwma.or.kr)

두개만 등록 요망 

경력증명서 사이트가 하나로 서비스에 통합됨

**Comment by lalalaho** [comment]
수정완료.
