### ISSUE TITLE
알선 > 이력조회 

### ISSUE THREAD

**Issue by YCKO0923** [lalalaho/cid#96]
1. 승인기능은 외부망 (홈페이지/모바일) 에서 들어올때만 활성화되고, 센터에서 알선한건 비노출 처리
2. 취업처리 > 근무등록 및 삭제 안됨
3. 근무 계약기간이 undefined ~ undefined 이렇게 출력
4. 알선장 발행 버튼 선택 시 무응답

**Comment by match23** [comment]
1,2,3, 완료
4. 알선장발행 1월3일 수정 예정

**Comment by YCKO0923** [comment]
4. 알선장 발행 버튼 클릭 시 404 에러
